In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [67]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [68]:
#lr = LogisticRegression()
#lr.fit(X_train,y_train)
#lr.score(X_test,y_test)

In [69]:
#sv = SVC()
#sv.fit(X_train,y_train)
#sv.score(X_test,y_test)

In [70]:
#rf= RandomForestClassifier()
#rf.fit(X_train,y_train)
#rf.score(X_test,y_test)

In [71]:
#from sklearn.model_selection import KFold
#kf=  KFold(n_splits=3)
#kf

In [73]:
#for train_index,test_index in kf.split([1,233,4,5,7,8,4,32,12]):
   # print(train_index,test_index)

In [47]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [48]:
from sklearn.model_selection import StratifiedKFold
SF = StratifiedKFold(n_splits=3)
SF

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [74]:
score_lin = []
score_sv = []
score_ranForest = []
for train_index,test_index in SF.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index],digits.data[test_index], digits.target[train_index],digits.target[test_index]
    
    score_lin.append(get_score(LogisticRegression(),X_train, X_test, y_train, y_test))
    score_sv.append(get_score(SVC(),X_train, X_test, y_train, y_test))
    score_ranForest.append(get_score(RandomForestClassifier(n_estimators=50),X_train, X_test, y_train, y_test))

    
    
    
    

C:\Users\Del\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Del\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = 

In [75]:
score_lin

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [76]:
score_ranForest

[0.9382303839732888, 0.9449081803005008, 0.9315525876460768]

In [77]:
score_sv

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [78]:
from sklearn.model_selection import cross_val_score

In [1]:
#cross_val_score(LogisticRegression(),digits.data,digits.target)

In [80]:
cross_val_score(SVC(), digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [82]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data,digits.target)

array([0.93611111, 0.89444444, 0.94707521, 0.95543175, 0.91643454])

In [83]:
cross_val_score(RandomForestClassifier(n_estimators=20), digits.data,digits.target)

array([0.91388889, 0.86666667, 0.94150418, 0.96657382, 0.91922006])

In [84]:
cross_val_score(RandomForestClassifier(n_estimators=60), digits.data,digits.target)

array([0.92777778, 0.88888889, 0.94986072, 0.96935933, 0.91922006])